/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.ui.admin;

import com.project.ecosystem.Business;
import com.project.ecosystem.DataLoader;
import com.project.enterprise.Enterprise;
import com.project.healthcare.PatientOrganization;
import com.project.location.City;
import com.project.location.Country;
import com.project.location.State;
import com.project.organization.Organization;
import com.project.patient.PatientProfile;
import com.project.person.Person;
import com.project.utils.SendEmail;
import com.project.utils.Validation;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anjali
 */
public class AddNewPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewPatientPanel
     */
    JPanel containerPanel;
    Enterprise enterprise;
    Organization patientOrganization;

    public AddNewPatientPanel(JPanel containerPanel, Enterprise enterprise) {
        initComponents();
        this.containerPanel = containerPanel;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org.getOrganizationType().equalsIgnoreCase(Organization.Type.PATIENT.getValue())) {
                patientOrganization = org;
                break;
            }
        }
        populateCityComboBox();
        populateInsuranceGroup();

    }

    public void resetFields() {
        txtFirst.setText("");
        txtLast.setText("");
        txtDOB.setText("");
        txtPhoneNumber.setText("");
        txtZipCode.setText("");
        txtMemberNumber.setText("");
    }
    public void populateCityComboBox() {

        for (Country country : DataLoader.getCountries()) {
            comboxCountry.addItem(country.getName());
            for (State state : country.getStates()) {
                comboxState.addItem(state.getName());
            }
        }
    }
    
    public void populateInsuranceGroup() {
        
        for(String entry : DataLoader.getInsuranceMap().keySet()) {
            comboBoxInsuranceGroup.addItem(entry);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        comboBoxInsuranceGroup = new javax.swing.JComboBox<>();
        txtMemberNumber = new javax.swing.JTextField();
        txtFirst = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblPhone = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblCountry = new javax.swing.JLabel();
        comboxCountry = new javax.swing.JComboBox<>();
        lblState = new javax.swing.JLabel();
        comboxState = new javax.swing.JComboBox<>();
        lblZipcode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnBack = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 14, 54), 5), "Create New Patient Profile", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18), new java.awt.Color(174, 14, 54))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 888));

        jLabel3.setBackground(new java.awt.Color(174, 14, 54));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(174, 14, 54));
        jLabel3.setText("Address details");

        lblName.setBackground(new java.awt.Color(174, 14, 54));
        lblName.setForeground(new java.awt.Color(174, 14, 54));
        lblName.setText("First Name:");

        jLabel4.setBackground(new java.awt.Color(174, 14, 54));
        jLabel4.setForeground(new java.awt.Color(174, 14, 54));
        jLabel4.setText("Insurance group:");

        lblDOB.setBackground(new java.awt.Color(174, 14, 54));
        lblDOB.setForeground(new java.awt.Color(174, 14, 54));
        lblDOB.setText("Date of Birth:");

        lblLastName.setBackground(new java.awt.Color(174, 14, 54));
        lblLastName.setForeground(new java.awt.Color(174, 14, 54));
        lblLastName.setText("Last Name:");

        comboBoxInsuranceGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anthem", "Blue Cross Blue Shield", "Cigna", "Harvard Medical School Insurance" }));
        comboBoxInsuranceGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxInsuranceGroupActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(174, 14, 54));
        jLabel5.setForeground(new java.awt.Color(174, 14, 54));
        jLabel5.setText("Insurance number:");

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(174, 14, 54));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblPhone.setBackground(new java.awt.Color(174, 14, 54));
        lblPhone.setForeground(new java.awt.Color(174, 14, 54));
        lblPhone.setText("Phone Number:");

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblCountry.setBackground(new java.awt.Color(174, 14, 54));
        lblCountry.setForeground(new java.awt.Color(174, 14, 54));
        lblCountry.setText("Country:");

        comboxCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USA", "India", "Canada" }));
        comboxCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxCountryItemStateChanged(evt);
            }
        });
        comboxCountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboxCountryFocusGained(evt);
            }
        });
        comboxCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCountryActionPerformed(evt);
            }
        });

        lblState.setBackground(new java.awt.Color(174, 14, 54));
        lblState.setForeground(new java.awt.Color(174, 14, 54));
        lblState.setText("State:");

        comboxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MA", "New York", "Califonia", "Maharashtra", "Gujarat", "Delhi", "Ontario", "Ottawa", "Montreal", " " }));
        comboxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxStateActionPerformed(evt);
            }
        });

        lblZipcode.setBackground(new java.awt.Color(174, 14, 54));
        lblZipcode.setForeground(new java.awt.Color(174, 14, 54));
        lblZipcode.setText("Zip code:");

        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(174, 14, 54));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(btnBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        lblEmail.setBackground(new java.awt.Color(174, 14, 54));
        lblEmail.setForeground(new java.awt.Color(174, 14, 54));
        lblEmail.setText("Email ID:");

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lblName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLastName)
                                            .addComponent(lblPhone)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDOB)
                                            .addComponent(lblEmail))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEmailId)
                                            .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblCountry)
                                .addGap(41, 41, 41)
                                .addComponent(comboxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(225, 225, 225)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblZipcode))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboxState, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxInsuranceGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDOB, txtFirst, txtLast, txtPhoneNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboxCountry, comboxState, txtZipCode});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDOB)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCountry)
                            .addComponent(comboxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState)
                            .addComponent(comboxState, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblZipcode)
                        .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxInsuranceGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDOB, txtEmailId, txtFirst, txtLast, txtPhoneNumber});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboxCountry, comboxState, txtZipCode});

    }// </editor-fold>//GEN-END:initComponents

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here

        boolean errorFlag = false;
        String errorFields = "Please enter correct values for following fields: \n";

        if (!Validation.validateTextFieldsForNonEmpty(txtFirst) || txtFirst.getText().equalsIgnoreCase("First Name")) {
            if (!Validation.validateTextFieldsForString(txtFirst)) {
                errorFields += "Invalid First Name\n";
                errorFlag = true;
            }
        }

        if (!Validation.validateTextFieldsForNonEmpty(txtLast) || txtLast.getText().equalsIgnoreCase("Last Name")) {
            if (!Validation.validateTextFieldsForString(txtLast)) {
                errorFields += "Invalid Last Name\n";
                errorFlag = true;
            }
        }

        //          add date validation
        if (!Validation.validateTextFieldsForNonEmpty(txtDOB) || txtDOB.getText().equalsIgnoreCase("Date of Birth")) {
            if (!Validation.validateTextFieldsForString(txtDOB)) {
                errorFields += "Invalid Date of Birth\n";
                errorFlag = true;
            }
        }

        if (!Validation.validateTextFieldsForPhoneNumber(txtPhoneNumber) || txtPhoneNumber.getText().equalsIgnoreCase("Phone Number")) {
            if (!Validation.validateTextFieldsForString(txtPhoneNumber)) {
                errorFields += "Invalid phone number\n";
                errorFlag = true;
            }
        }

        if (!Validation.validateTextFieldsForNonEmpty(txtMemberNumber) || txtMemberNumber.getText().equalsIgnoreCase("Insurance number")) {

            errorFields += "Invalid insurance member number\n";
            errorFlag = true;

        }

        if (!errorFlag) {
            Person person = new PatientProfile();
            PatientProfile patientProfile = (PatientProfile) person;
            patientOrganization.getPersonDirectory().getPersonList().add(person);
            patientProfile.setfName(txtFirst.getText());
            patientProfile.setlName(txtLast.getText());
            patientProfile.setPhoneNum(txtPhoneNumber.getText());
            patientProfile.setEmailId(txtEmailId.getText());
            patientProfile.getUserAccount().setUserName(person.getfName().substring(0, 2) + person.getlName().substring(0, 3) + person.getId());
            patientProfile.getUserAccount().setPassword(person.getPhoneNum()); //
            patientProfile.setInsuranceGroup((String) comboBoxInsuranceGroup.getSelectedItem());
            patientProfile.setInsuranceNumber(txtMemberNumber.getText().trim());
            patientProfile.getAddress().setCountry((String) comboxCountry.getSelectedItem());
            patientProfile.getAddress().setState((String) comboxState.getSelectedItem());

            JOptionPane.showMessageDialog(this, "New patient created successfully with : " + person.getId(),
                    "FORM SUCCESS", JOptionPane.INFORMATION_MESSAGE);

            resetFields();

        } else {
            JOptionPane.showMessageDialog(this, "Incorrect form fields: " + errorFields,
                    "FORM ERROR", JOptionPane.ERROR_MESSAGE);
        }
        SendEmail sendEmail = new SendEmail(txtEmailId.getText(), 
                "Welcome" + " " + txtFirst.getText(), "Your Profile has been created");
        


    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboxCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxCountryItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCountryItemStateChanged

    private void comboxCountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboxCountryFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCountryFocusGained

    private void comboxCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCountryActionPerformed

    private void comboxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxStateActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        containerPanel.remove(this);
        CardLayout cardLayout = (CardLayout) containerPanel.getLayout();
        cardLayout.previous(containerPanel);

        //SplitPane.setRightComponent(loginPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboBoxInsuranceGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxInsuranceGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxInsuranceGroupActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBoxInsuranceGroup;
    private javax.swing.JComboBox<String> comboxCountry;
    private javax.swing.JComboBox<String> comboxState;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtMemberNumber;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

   
}
