/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.ui.admin;

import com.project.donor.DonorProfile;
import com.project.ecosystem.DataLoader;
import com.project.enterprise.Enterprise;
import com.project.healthcare.DonorOrganization;
import com.project.location.Country;
import com.project.location.State;
import com.project.organization.Organization;
import com.project.person.Person;
import com.project.utils.Validation;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anjali
 */
public class AddNewDonorPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewDonorPanel
     */
    
    JPanel containerPanel;
    Enterprise enterprise;
    Organization donorOrganization;
    public AddNewDonorPanel(JPanel containerPanel,Enterprise enterprise) {
        initComponents();
        this.containerPanel = containerPanel;
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if(org.getOrganizationType().equalsIgnoreCase(Organization.Type.DONOR.getValue())) {
                donorOrganization = org;
                break;
            }
        }   
        populateCityComboBox();
    }
    
     public void resetFields() {
        txtFirst.setText("");
        txtLast.setText("");
        txtDOB.setText("");
        txtPhoneNumber.setText("");
        txtZipCode.setText("");
       }
     
      public void populateCityComboBox() {

        for (Country country : DataLoader.getCountries()) {
            comboxCountry.addItem(country.getName());
            for (State state : country.getStates()) {
                comboxState.addItem(state.getName());
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnBack = new javax.swing.JButton();
        txtFirst = new javax.swing.JTextField();
        txtLast = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblPhone = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        comboxState = new javax.swing.JComboBox<>();
        lblZipcode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        comboxCountry = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 14, 54), 5), "Create New Donor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18), new java.awt.Color(174, 14, 54))); // NOI18N
        setForeground(new java.awt.Color(174, 14, 54));
        setPreferredSize(new java.awt.Dimension(1100, 800));

        btnBack.setBackground(new java.awt.Color(174, 14, 54));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(btnBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(174, 14, 54));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblPhone.setForeground(new java.awt.Color(174, 14, 54));
        lblPhone.setText("Phone Number:");

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblState.setForeground(new java.awt.Color(174, 14, 54));
        lblState.setText("State:");

        comboxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MA", "New York", "Califonia", "Maharashtra", "Gujarat", "Delhi", "Ontario", "Ottawa", "Montreal", " " }));
        comboxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxStateActionPerformed(evt);
            }
        });

        lblZipcode.setForeground(new java.awt.Color(174, 14, 54));
        lblZipcode.setText("Zip code:");

        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(174, 14, 54));
        jLabel3.setText("Address details");

        lblName.setForeground(new java.awt.Color(174, 14, 54));
        lblName.setText("First Name:");

        lblDOB.setForeground(new java.awt.Color(174, 14, 54));
        lblDOB.setText("Date of Birth:");

        lblLastName.setForeground(new java.awt.Color(174, 14, 54));
        lblLastName.setText("Last Name:");

        lblCountry.setForeground(new java.awt.Color(174, 14, 54));
        lblCountry.setText("Country:");

        comboxCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USA", "India", "Canada", " " }));
        comboxCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxCountryItemStateChanged(evt);
            }
        });
        comboxCountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboxCountryFocusGained(evt);
            }
        });
        comboxCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCountry)
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblZipcode))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboxState, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLastName)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtLast))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPhone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboxCountry, comboxState, txtDOB, txtFirst, txtPhoneNumber, txtZipCode});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountry)
                    .addComponent(comboxState, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipcode))
                .addGap(44, 44, 44)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboxCountry, comboxState, txtDOB, txtFirst, txtLast, txtPhoneNumber, txtZipCode});

    }// </editor-fold>//GEN-END:initComponents

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here

        boolean errorFlag = false;
        String errorFields = "Please enter correct values for following fields: \n";

        if (!Validation.validateTextFieldsForNonEmpty(txtFirst) || txtFirst.getText().equalsIgnoreCase("First Name")) {
            if (!Validation.validateTextFieldsForString(txtFirst)) {
                errorFields += "Invalid First Name\n";
                errorFlag = true;
            }
        }

        if (!Validation.validateTextFieldsForNonEmpty(txtLast) || txtLast.getText().equalsIgnoreCase("Last Name")) {
            if (!Validation.validateTextFieldsForString(txtLast)) {
                errorFields += "Invalid Last Name\n";
                errorFlag = true;
            }
        }

        //          add date validation
        if (!Validation.validateTextFieldsForNonEmpty(txtDOB) || txtDOB.getText().equalsIgnoreCase("Date of Birth")) {
            if (!Validation.validateTextFieldsForString(txtDOB)) {
                errorFields += "Invalid Date of Birth\n";
                errorFlag = true;
            }
        }

        if (!Validation.validateTextFieldsForPhoneNumber(txtPhoneNumber) || txtPhoneNumber.getText().equalsIgnoreCase("phone number")) {
            if (!Validation.validateTextFieldsForString(txtPhoneNumber)) {
                errorFields += "Invalid phone number\n";
                errorFlag = true;
            }
        }

        if (!errorFlag) {
            Person person = new DonorProfile();
            donorOrganization.getPersonDirectory().getPersonList().add(person);
            person.setfName(txtFirst.getText());
            person.setlName(txtLast.getText());
            person.setPhoneNum(txtPhoneNumber.getText());
            person.getUserAccount().setUserName(person.getfName().substring(0, 2) + person.getlName().substring(0, 3) + person.getId());
            person.getUserAccount().setPassword(person.getPhoneNum()); //

            JOptionPane.showMessageDialog(this, "New Donor created successfully with : " + person.getId(),
                "FORM SUCCESS", JOptionPane.INFORMATION_MESSAGE);

            resetFields();

        }

        else {
            JOptionPane.showMessageDialog(this, "Incorrect form fields: " + errorFields,
                "FORM ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        containerPanel.remove(this);
        CardLayout cardLayout = (CardLayout) containerPanel.getLayout();
        cardLayout.previous(containerPanel);

        //SplitPane.setRightComponent(loginPanel);

    }//GEN-LAST:event_btnBackActionPerformed

    private void comboxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxStateActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void comboxCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxCountryItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCountryItemStateChanged

    private void comboxCountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboxCountryFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCountryFocusGained

    private void comboxCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCountryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboxCountry;
    private javax.swing.JComboBox<String> comboxState;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void setPreferredSize(int i, int i0) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
