/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.ui.pharmacy;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author bhavinbhatia
 */
public class InventoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryPanel
     */
    public InventoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderQuantity = new javax.swing.JSlider();
        txtPrice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedicineStock = new javax.swing.JTable();
        btnAddMed = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUpdateMed = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDeleteMed = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        txtMedId = new javax.swing.JTextField();

        sliderQuantity.setForeground(new java.awt.Color(174, 14, 54));
        sliderQuantity.setMajorTickSpacing(10);
        sliderQuantity.setPaintLabels(true);
        sliderQuantity.setPaintTicks(true);
        sliderQuantity.setSnapToTicks(true);
        sliderQuantity.setToolTipText("");
        sliderQuantity.setValue(0);

        tblMedicineStock.setBackground(new java.awt.Color(252, 246, 245));
        tblMedicineStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Drud Id", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(tblMedicineStock);

        btnAddMed.setBackground(new java.awt.Color(174, 14, 54));
        btnAddMed.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMed.setText("Add ");
        btnAddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(174, 14, 54));
        jLabel1.setText(" Name: ");

        btnUpdateMed.setBackground(new java.awt.Color(174, 14, 54));
        btnUpdateMed.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateMed.setText("Update");

        jLabel2.setForeground(new java.awt.Color(174, 14, 54));
        jLabel2.setText("Medicine Id:");

        btnDeleteMed.setBackground(new java.awt.Color(174, 14, 54));
        btnDeleteMed.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteMed.setText("Delete");

        jLabel3.setForeground(new java.awt.Color(174, 14, 54));
        jLabel3.setText("Quantity:");

        jLabel4.setForeground(new java.awt.Color(174, 14, 54));
        jLabel4.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddMed, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateMed)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteMed)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtMedName)
                            .addComponent(txtMedId)
                            .addComponent(txtPrice)
                            .addComponent(sliderQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(205, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddMed, btnDeleteMed, btnUpdateMed});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sliderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMed)
                    .addComponent(btnUpdateMed)
                    .addComponent(btnDeleteMed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddMed, btnDeleteMed, btnUpdateMed});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblMedicineStock.getModel();
        model.addRow(new Object[]{txtMedName.getText(), txtMedId.getText(),
            sliderQuantity.getValue(), txtPrice.getText()});

    }//GEN-LAST:event_btnAddMedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMed;
    private javax.swing.JButton btnDeleteMed;
    private javax.swing.JButton btnUpdateMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider sliderQuantity;
    private javax.swing.JTable tblMedicineStock;
    private javax.swing.JTextField txtMedId;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
