/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.ui.hospital;

import com.project.db4o.DB4OUtil;
import com.project.ecosystem.Business;
import com.project.ecosystem.Ecosystem;
import com.project.role.Role;
import com.project.utils.AuthenticationUtil;
import com.project.utils.Utils;
import com.project.utils.Validation;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anjali
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPage
     */
    JPanel containerPanel;
    private Business business;

    private DB4OUtil db4oUtil = DB4OUtil.getInstance();

    public LoginPanel(JPanel containerPanel, Business business) {
        initComponents();
        this.containerPanel = containerPanel;
        this.business = business;
    }
    
    
//    public void populateOrgComboBox() {
//        jCombRoleSelector.removeAllItems();
//        jCombRoleSelector.addItem("System Admin");
//        jCombRoleSelector.addItem("Enterprise Admin");
//        jCombRoleSelector.addItem("Organization Admin");
//        jCombRoleSelector.addItem("Doctor");
//        jCombRoleSelector.addItem("Patient");
//        jCombRoleSelector.addItem("Recipient");
//        jCombRoleSelector.addItem("Blood Inventory Manager");
//        jCombRoleSelector.addItem("Blood Donation Manager");
//       
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtPswd = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 14, 54), 2));
        setForeground(new java.awt.Color(16, 212, 212));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jLayeredPane1.setBackground(new java.awt.Color(153, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 14, 54), 5), "User Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 24), new java.awt.Color(174, 14, 54))); // NOI18N
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1200, 800));

        txtPswd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPswdFocusGained(evt);
            }
        });
        txtPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswdActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(174, 14, 54));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(174, 14, 54));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 14, 54));
        jLabel1.setText("USERNAME:");

        jLabel2.setBackground(new java.awt.Color(174, 14, 54));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(174, 14, 54));
        jLabel2.setText("PASSWORD:");

        txtUserName.setText("Enter Your UserName");
        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
        });
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(txtPswd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtPswd, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPswd, txtUserName});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPswd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogin, txtPswd, txtUserName});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(412, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
         btnLogin.setEnabled(true);

        btnLogin.setEnabled(true);
        AuthenticationUtil authenticate = new AuthenticationUtil(business, containerPanel);
        String userName = txtUserName.getText();

        String password = String.valueOf(txtPswd.getPassword());

        boolean loginErrorFlag = false;
        String loginErrorMsg = "";
        if (Validation.validateTextFieldsForNonEmpty(txtUserName) == false || userName.equalsIgnoreCase("Enter Your UserName")) {
            loginErrorFlag = true;
            loginErrorMsg = "Username cannot be blank";
        }

        if (!Validation.validateTextFieldsForNonEmpty(txtPswd)) {
            loginErrorFlag = true;
            loginErrorMsg += "\n Password cannot be blank";
        }

        if (loginErrorFlag == true) {
            JOptionPane.showMessageDialog(null, loginErrorMsg, "Login Error Message: ", JOptionPane.ERROR_MESSAGE);
            return;
        } else {

            authenticate.authenticateUser(userName, password);



        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswdActionPerformed

    private void txtPswdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPswdFocusGained
        // TODO add your handling code here:

        if (String.valueOf(txtPswd.getPassword()).trim().equalsIgnoreCase("Password:")) {
            txtPswd.setText("");
        }

    }//GEN-LAST:event_txtPswdFocusGained

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
        // TODO add your handling code here:

        if (txtUserName.getText().equalsIgnoreCase("Enter Your UserName")) {
            txtUserName.setText("");
            txtUserName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtUserNameFocusGained

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField txtPswd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
